#Google Account
ACCOUNT: yougoogleaccount@gmail.com

#DB Server
DB:
    TYPE: mysql
    HOST: localhost
    PORT: 3306
    USER: user
    PASSWORD: password
    DATABASE: database

#Configuration for web.py
CACHE: False
DEBUG: True
URL_MAPPING:
    [
        '/blog/(.+).html', 'Article', 
        '/cat/(.+)',       'Category', 
        '/tag/(.+)',       'Tag', 
        '/(.+)',           'Page', 
        '/',               'Index'
    ]
